FROM alpine:3.8

LABEL maintainer="gaozhiqiang <gaozhiqiang@solomonlinux.com>"

ENV NGINX_VERSION=1.15.6 \
	NGINX_ROOT=/usr/share/nginx/html/

#ADD nginx-${NGINX_VERSION}.tar.gz /usr/local/src/

RUN \
	CONFIG="\
		--prefix=/usr/local/nginx \
		--sbin-path=/usr/local/nginx/sbin/nginx \
		--modules-path=/usr/local/nginx/modules \
		--conf-path=/etc/nginx/nginx.conf \
		--error-log-path=/var/log/nginx/error.log \
		--http-log-path=/var/log/nginx/access.log \
		--pid-path=/var/run/nginx.pid \
		--lock-path=/var/run/nginx.lock \
		--http-client-body-temp-path=/var/cache/nginx/client_temp \
		--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
		--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
		--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
		--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
		--user=nginx \
		--group=nginx \
		--with-http_ssl_module \
		--with-http_realip_module \
		--with-http_addition_module \
		--with-http_sub_module \
		--with-http_dav_module \
		--with-http_flv_module \
		--with-http_mp4_module \
		--with-http_gunzip_module \
		--with-http_gzip_static_module \
		--with-http_random_index_module \
		--with-http_secure_link_module \
		--with-http_stub_status_module \
		--with-http_auth_request_module \
		--with-http_xslt_module=dynamic \
		--with-http_image_filter_module=dynamic \
		--with-http_geoip_module=dynamic \
		--with-threads \
		--with-stream \
		--with-stream_ssl_module \
		--with-stream_ssl_preread_module \
		--with-stream_realip_module \
		--with-stream_geoip_module=dynamic \
		--with-http_slice_module \
		--with-mail \
		--with-mail_ssl_module \
		--with-compat \
		--with-file-aio \
		--with-http_v2_module \			
		"\
	&& apk add --no-cache --virtual .build-deps \
		curl \
		gcc \
		libc-dev \
		linux-headers \
		pcre-dev \
		openssl-dev \
		libxslt-dev \
		gd-dev \
		geoip-dev \
		make \
		zlib-dev \
	&& addgroup -S nginx \
	&& adduser -s /sbin/nologin -G nginx -S -D nginx \
	&& curl -sfSL https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz -o nginx.tar.gz \
	&& tar xf nginx.tar.gz \
	&& rm -f nginx.tar.gz \
	&& cd nginx-${NGINX_VERSION} \
	&& ./configure ${CONFIG} \
	#&& make -j$(getconf _NPROCESSORS_ONLY) \
	&& make -j1 \
	&& make install \
	&& mkdir -p /etc/nginx/conf.d/ \
	&& mkdir -p ${NGINX_ROOT} \
	&& install -m644 html/index.html /usr/share/nginx/html/ \
	&& install -m644 html/50x.html /usr/share/nginx/html/ \
	&& cd .. \
	&& rm -rf nginx-${NGINX_VERSION} \
	&& mkdir -p /var/cache/nginx/ \
	&& ln -sf /dev/stdout /var/log/nginx/acess.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

COPY index.html ${NGINX_ROOT}
COPY nginx.conf /etc/nginx/
COPY nginx.conf.default /etc/nginx/conf.d/www.conf

EXPOSE 80/tcp

STOPSIGNAL SIGTERM
CMD ["/usr/local/nginx/sbin/nginx","-g","daemon off;"]
